import ComplexitySensitiveEnergy.External.Inputs
import ComplexitySensitiveEnergy.Flagged.CertifiedTheorem11
import ComplexitySensitiveEnergy.QuadraticThreefold.FiberRank
import ComplexitySensitiveEnergy.QuadraticThreefold.NoLines
import ComplexitySensitiveEnergy.QuadraticThreefold.Theorem12
import ComplexitySensitiveEnergy.QuadraticThreefold.TwoCrossing
import ComplexitySensitiveEnergy.Weighted.Main
import ComplexitySensitiveEnergy.Weighted.RestrictedStrong
import ComplexitySensitiveEnergy.Turning.ConvexInterpolation
import ComplexitySensitiveEnergy.Turning.ConcaveReduction
import ComplexitySensitiveEnergy.Turning.ComplexityExistence
import ComplexitySensitiveEnergy.Turning.DyadicAssembly
import ComplexitySensitiveEnergy.Turning.Main
import ComplexitySensitiveEnergy.Turning.PacketExample
import ComplexitySensitiveEnergy.Turning.SlopeInvariance
import ComplexitySensitiveEnergy.Turning.StripExponent
import ComplexitySensitiveEnergy.Turning.Theorem14

/-!
# Kernel dependency audit

Representative internal results are printed here so a build records their
kernel dependencies.  The literature and standard analytic results remain
ordinary proposition-valued inputs; this project declares no global axiom.
-/

#check ComplexitySensitiveEnergy.Theorem11Statement
#check ComplexitySensitiveEnergy.QuadraticThreefold.Theorem12Statement
#check ComplexitySensitiveEnergy.Theorem13Statement
#check ComplexitySensitiveEnergy.Turning.Theorem14Statement
#check ComplexitySensitiveEnergy.External.Inputs

#print axioms ComplexitySensitiveEnergy.differenceEnergy_eq_addEnergy
#print axioms ComplexitySensitiveEnergy.energy_biUnion_le_card_cube_mul_sum_nat
#print axioms ComplexitySensitiveEnergy.two_mul_card_sq_sub_card_le_energy
#print axioms ComplexitySensitiveEnergy.PaperVariety.exceptionalEnergy_le
#print axioms ComplexitySensitiveEnergy.PaperVariety.CrossingCertificate.two_crossing_local_lambda_four
#print axioms ComplexitySensitiveEnergy.PaperVariety.theorem11_of_recurrenceInputs

#print axioms ComplexitySensitiveEnergy.QuadraticThreefold.graphMap_no_nontrivial_midpoint
#print axioms ComplexitySensitiveEnergy.QuadraticThreefold.rankDropGramMajorant_le_seven
#print axioms ComplexitySensitiveEnergy.QuadraticThreefold.SimplePencil.canonicalFiber_rank_lt_two_direction
#print axioms ComplexitySensitiveEnergy.QuadraticThreefold.ThreefoldCrossingCertificate.two_crossing_rankDrop
#print axioms ComplexitySensitiveEnergy.QuadraticThreefold.quadraticThreefoldEnergy_of_recurrenceInputs
#print axioms ComplexitySensitiveEnergy.QuadraticThreefold.theorem12_of_recurrenceInputs
#print axioms ComplexitySensitiveEnergy.QuadraticThreefold.theorem12_of_granularRecurrenceInputs

#print axioms ComplexitySensitiveEnergy.weightedCorrelationSquareSum_le
#print axioms ComplexitySensitiveEnergy.finiteLpNorm_two_le_energy_fourthRoots
#print axioms ComplexitySensitiveEnergy.youngConvolutionBound_one_two
#print axioms ComplexitySensitiveEnergy.verify_theorem13_instance
#print axioms ComplexitySensitiveEnergy.theorem13_of_endpointInputs
#print axioms ComplexitySensitiveEnergy.fourierL2FourthBound_of_hereditary
#print axioms ComplexitySensitiveEnergy.theorem13_internal

#print axioms ComplexitySensitiveEnergy.Turning.certificateOfFiniteAffineSupport
#print axioms ComplexitySensitiveEnergy.Turning.convexInterpolationCertificate_of_adjacentSlopes
#print axioms ComplexitySensitiveEnergy.Turning.cushmanDemeterWu_concave
#print axioms ComplexitySensitiveEnergy.Turning.dyadic_assembly_sixth_power_natMass
#print axioms ComplexitySensitiveEnergy.Turning.turningComplexityUpper_of_dyadicInputs
#print axioms ComplexitySensitiveEnergy.Turning.exists_unique_hasTurningComplexity
#print axioms ComplexitySensitiveEnergy.Turning.hasTurningComplexity_change_of_complement_iff
#print axioms ComplexitySensitiveEnergy.Turning.hasTurningComplexity_complements_iff
#print axioms ComplexitySensitiveEnergy.Turning.stripTheta_exponent
#print axioms ComplexitySensitiveEnergy.Turning.J3_powerCurve_between
#print axioms ComplexitySensitiveEnergy.Turning.canonicalPacketConfiguration_properties
#print axioms ComplexitySensitiveEnergy.Turning.resetPacket_forces_linear_block_count
#print axioms ComplexitySensitiveEnergy.Turning.theorem14_of_dyadicInputs
